apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-migration-og
  namespace: openshift-migration
  annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "-10"
spec:
  targetNamespaces:
    - openshift-migration
  upgradeStrategy: Default
