# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   annotations:
#     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
#     argocd.argoproj.io/sync-wave: "8"
#   name: eso-secret-store
# spec:
#   provider:
#     aws:
#       region: us-east-2
#       service: SecretsManager

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  annotations:
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
      argocd.argoproj.io/sync-wave: "8"
  name: gitops-secretstore
  namespace: openshift-gitops
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2