apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: serverless-operator
  namespace: openshift-serverless
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
spec:
  channel: stable
  name: serverless-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace