apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: gitops-plugin
spec:
  backend:
    service:
      basePath: /
      name: gitops-plugin
      namespace: openshift-gitops
      port: 9001
    type: Service
  displayName: GitOps Plugin
  i18n:
    loadType: PreLoad
  # proxy:
  # - alias: proxy
  #   authorization: UserToken
  #   endpoint:
  #     service:
  #       name: gitops-plugin-proxy
  #       namespace: gitops-admin-plugin
  #       port: 8443
  #     type: Service